### ISSUE TITLE
Debug on IOS device error

### ISSUE THREAD

**Issue by hengway1989** [myflashlab/GCM-ANE#32]
Hi, as subject, please help on this issue. When I include the gcm ANE, and debug on IOS, flash builder will show below error:
Error occurred while packaging the application:

duplicate symbol _didReceiveRemoteNotificationFetchCompletionHandler in:
    /var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/89bcd79d-6d9a-42c6-bce6-f6107c67010e/libcom.myflashlab.air.extensions.dependency.overrideAir.a(exOverrideNative.o)
    /var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/3fd55f24-6b4e-4913-9615-03a2fadc0888/libcom.myflashlab.air.extensions.gcm.a(exGcm.o)
duplicate symbol _didReceiveRemoteNotification in:
    /var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/89bcd79d-6d9a-42c6-bce6-f6107c67010e/libcom.myflashlab.air.extensions.dependency.overrideAir.a(exOverrideNative.o)
    /var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/3fd55f24-6b4e-4913-9615-03a2fadc0888/libcom.myflashlab.air.extensions.gcm.a(exGcm.o)
ld: 2 duplicate symbols for architecture arm64
duplicate symbol _didReceiveRemoteNotificationFetchCompletionHandler in:
    /var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/89bcd79d-6d9a-42c6-bce6-f6107c67010e/libcom.myflashlab.air.extensions.dependency.overrideAir.a(exOverrideNative.o)
    /var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/3fd55f24-6b4e-4913-9615-03a2fadc0888/libcom.myflashlab.air.extensions.gcm.a(exGcm.o)
duplicate symbol _didReceiveRemoteNotification in:
    /var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/89bcd79d-6d9a-42c6-bce6-f6107c67010e/libcom.myflashlab.air.extensions.dependency.overrideAir.a(exOverrideNative.o)
    /var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/3fd55f24-6b4e-4913-9615-03a2fadc0888/libcom.myflashlab.air.extensions.gcm.a(exGcm.o)
ld: 2 duplicate symbols for architecture armv7
Compilation failed while executing : ld64

After I check the option of Hide ANE-Library-Symbols, it will return error message as below:
Compilation failed while executing : ld64

Please help advice, environment as below: 
Mac sierra
Flash builder 4.7
AIR 24
Ipad mini 4

**Comment by hengway1989** [comment]
Hi, already found the ANE cause this issue, found after I upgrade OverrideAir ANE from 3.0.0 to 4.0.0 then will occur this issue, please advice. Thank you

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
